[bumpversion]
commit = true
tag = true
current_version = 44.44.44
message = 'Bump version: "{current_version}" â†’ "{new_version}" ***NO_CI***'

[bumpversion:file:VERSION]

[[files]]
path = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'
